name: ber
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - geopandas
  - poetry
  - ipython
  - requests
  - dask
  - pyarrow
  - tqdm
  - pre-commit
  - jupyter
  - jupyter_contrib_nbextensions
  - seaborn
  - matplotlib
  - descartes
  - numexpr
  - pip
  - pip:
    - seai-deap
    - git+https://github.com/codema-dev/berpublicsearch
