name: berpublicsearch
channels:
  - conda-forge
  - defaults
dependencies:
  - python

  - geopandas
  - dask
  - requests

  - pyarrow
  - numexpr
  - tqdm
  
  - seaborn
  - matplotlib
  - descartes

  - pip
  - pip:
    - seai-deap
    - berpublicsearch
