[tool.poetry]
name = "berpublicsearch"
version = "0.1.0"
description = "Sets up a sandbox notebook environment for querying SEAI's BER Public search database"
authors = ["Rowan Molony <rowan.molony@codema.ie>", "Oisin Doherty <oisin.doherty@codema.ie>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.6.9"
google-colab = "^1.0.0"
prefect = "*"
requests = "*"
pandas = "*"
tqdm = "^4.54.1"
dask = {version = "*", extras = ["dataframe"]}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
